## 파이썬의 기본문법 중 Numpy부터

In [5]:
import numpy as np  # 넘파이 모듈 불러오기, 설치는 anaconda의 경우 conda install numpy

### 넘파이 배열 생성하기

In [6]:
x = np.array([1.0, 2.0, 3.0])
print(x)
print(type(x))

[1. 2. 3.]
<class 'numpy.ndarray'>


### 넘파이 산술 연산

In [11]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(f'x + y = {x + y}')
print(f'x - y = {x - y}')
print(f'x * y = {x * y}')
print(f'x / y = {x / y}')

x + y = [3. 6. 9.]
x - y = [-1. -2. -3.]
x * y = [ 2.  8. 18.]
x / y = [0.5 0.5 0.5]


위의 연산은 x와 y의 원소수가 같아야 합니다. 그렇지 않으면 오류가 발생합니다. <br>
원소별은 영어로 'element-wise' <br>
원소별 곱은 'element-wise product'

In [19]:
#넘파이 배열과 하나의 스칼라값의 산술연산이 가능합니다.
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

### 넘파이의 N차원 배열

In [17]:
A = np.array([[1,2], [3,4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int32


In [18]:
# N차원 배열의 산술연산
B = np.array([[3, 0], [0, 6]])
print(A + B)
print(A * B)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


In [21]:
print(A)
A * 10

[[1 2]
 [3 4]]


array([[10, 20],
       [30, 40]])

### 브로드캐스트
넘파이에서는 형상이 다른 즉, 차원이 다른 배열끼리도 계산할 수 있습니다.<br>
스칼라 값을 곱할 시  배열이 확장 되는데 이런 기능을 브로드캐스트라고 합니다.

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

### 원소접근
원소의 인덱스는 0부터 시작합니다.

In [42]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X, end='\n\n')
print(X[0], end='\n\n')
print(X[0][1])

[[51 55]
 [14 19]
 [ 0  4]]

[51 55]

55


In [43]:
#for문으로 원소에 접근
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [47]:
#인덱스를 배열로 지정하여 한번에 여러 원소에 접근하는법
X = X.flatten() # X를 1차원 배열로 평탄화
print(X)
X[np.array([0, 2, 4])] #인덱스가 0, 2, 4인 원소만 얻기

[51 55 14 19  0  4]


array([51, 14,  0])

In [49]:
#특정 조건 원소얻기
print(X > 15)

print(X[X>15])

[ True  True False  True False False]
[51 55 19]
